### ISSUE TITLE
Countdown to Midnight Thoughts 

### ISSUE THREAD

**Issue by m00se333** [learn-co-curriculum/countdown-to-midnight#12]
This lab was useful as a practice in a countdown/subtraction scenario as well as an introduction to the ```sleep``` method.

However I don't think that making us create the new method ```countdown_with_sleep``` that accepts an argument of at least 5 seconds was the best way of achieving this. I passed the ```learn``` test with the following code: 

```
def countdown_with_sleep(x)
  sleep x
end


def countdown(number)
  while number > 0
    puts "#{number} SECOND(S)!"
    number -= 1
  end
  return "HAPPY NEW YEAR!"
end
```

I think that students should have been instructed to code as follows: 

```
def countdown(number)
  while number > 0
    puts "#{number} SECOND(S)!"
    number -= 1
    sleep 1
  end
  return "HAPPY NEW YEAR!"
end
```

While it may be confusing at first for students who are just being introduced to Ruby I think that this approach, doing away with an extra method and inserting the sleep program into the ```countdown(number)``` method itself, is more in keeping with the overarching point of readability and near intuitive nature of reading Ruby code. We've already been introduced to ```gets.chomp``` this cool extra function, ```sleep``` doesn't seem like too much of a burden content-wise this unit.

Furthermore it achieves the true spirit of the instruction that reads (in #4):

*"Our Ruby program executes so quickly that is doesn't actually count down at the speed of one per second per number.  See if you can make the loop pause for one second each trip around(hint)"*

**Comment by SophieDeBenedetto** [comment]
hi @m00se333, the manner in which you passed the tests is correct and that is in fact what you are being instructed to do in the reading. Thanks for your input though. 

Closing issue
