### ISSUE TITLE
returns vs. puts "Happy New Year!"

### ISSUE THREAD

**Issue by psmathers** [learn-co-curriculum/countdown-to-midnight#14]
This lesson was confusing, and felt like an unnecessary trick question. It doesn't make sense to count down to "Happy New Year", but then NOT output "Happy New Year!" Everything in my codes was working except "return" instead of "puts", and I spent an hour trying to get them to pass the test.

**Comment by AnnJohn** [comment]
Hi @psmathers thanks for raising the issue. Since we want students to understand the difference between puts vs. return, that's why we included this and we added the hint in the instructions on return values.
