### ISSUE TITLE
Yield and Blocks Code Along Tests Do Not Match Content

### ISSUE THREAD

**Issue by isomericmagic** [learn-co-curriculum/countdown-to-midnight#15]
The tests in the hello_spec.rb file for this lesson do not match the content of the lesson itself.

Specifically, the lesson says this:

![lessoncontent](https://cloud.githubusercontent.com/assets/17525429/23532370/04ea3976-ff60-11e6-9a0c-07d65244e2ad.PNG)

But the hello_spec.rb file that is used to test the lesson contains 3 different tests that do not appear to be mentioned anywhere in the lesson:

![rspec](https://cloud.githubusercontent.com/assets/17525429/23532457/64051494-ff60-11e6-9d09-3305ef43c456.PNG)

Another student was able to share the hello_spec.rb file that was included when he did the lesson and updating mine to match that one was enough to get the lesson to pass, but I believe either the lesson or the test file should be updated.

**Comment by Joll59** [comment]
@isomericmagic I believe you are currently posting this issue on the wrong lab. If you are still having an issue with your lab please ask questions using Slack or the ask a question feature on Learn.co.

Closing issue for now.
