### ISSUE TITLE
Ruby files don't execute in the terminal

### ISSUE THREAD

**Issue by buckethead1986** [learn-co-curriculum/countdown-to-midnight#16]
Mac OS 10.12.6, I installed everything according to flatiron schools 'manual setup', but when I start the terminal, I get an error of 'Could not source '/Users/robertpeck/.rvm/scripts/version' as file does not exist. RVM will likely not work as expected.' 
Plus, when I create files from the terminal ('touch math.rb', 'atom math.rb', the entire program, written in the Learn IDE is 'puts 1 + 2'), typing 'ruby math.rb' in the terminal outputs nothing.

I'm sure its a simple fix, but I don't know how to fix it. Help!

**Comment by buckethead1986** [comment]
So, 'touch' doesn't actually create a file. You have to save it, but ctrl-s doesn't save a file just made with 'touch'. So you have to save as, or try to close the file window, and it asks if you want to save changes. 
This leads to an endless loop of trying to save changes, the file is undefined, save as?, that file already exists, replace it?, the file is undefined, save as?, that file already exists, replace it?, but canceling this loop saves the file and allows it to be executed from the terminal.

What the hell.

**Comment by buckethead1986** [comment]
Thanks for the reply!

I'm doing the exact same commands, and for some reason now 'touch' is
making files, and I can search for them on the computer, but saving them
still leads to that infinite loop. I don't know why, but I just tried it
again, and the files still can't be saved normally. I'm sure there's
something simple I messed up, but I don't have any idea what that could be.
What information do you need? This Mac is 2 weeks old, and I followed the
instructions on 'Manually configure your environment for OS X' from the
people at Learn.

I'm trying to create, open, and run ruby files from the OS terminal, but
the Learn IDE is what the files actually open in with 'atom', and where I'm
writing my code. I am not using the Learn terminal.

I reinstalled rvm and it looks like it worked, thank you.

Thanks for the tip. That was my first GitHub Question, because the Learn
Ask a Question sent me to other students, but they didn't respond, and
after a few days of no answers, I looked elsewhere.

Robert

**Comment by gj** [comment]
Here's a [brief explainer](http://help.learn.co/the-learn-ide/the-basics-of-the-learn-ide/how-the-learn-ide-works) on what the Learn IDE is.

The manual environment setup instructions are generally for people who **don't** use the IDE. It's easier to keep it as an either-or proposition. If you want to use the IDE, just use the IDE and don't mess with IDE-created files in your local environment. If you don't want to use the IDE, then [uninstall it](http://help.learn.co/the-learn-ide/ide-settings/deleting-the-ide) and install vanilla [Atom](https://atom.io/) as your text editor.

Hope that helps! 💙

**Comment by buckethead1986** [comment]
Thank you so much. The instructions were a little odd, because step 1 is
'delete the Learn IDE' and step 1 of the first lab is 'Open the Lean IDE',
so I reinstalled it. I also installed Atom, but am currently using the
Learn IDE for the pre-work simply because of familiarity from the intro
course.

Robert

**Comment by gj** [comment]
We recommend everyone stick with the Learn IDE until they feel comfortable debugging environment issues on their own. The IDE gives us a nice, standardized system that we are familiar with and can easily assist students in debugging. We don't support local environment issues because it just wouldn't be feasible — too many different possible configurations out there, so it'd be much more difficult to nail down the root cause of an problem.

Gonna close out this issue now — hope your coding journey goes more smoothly from here on! 🙂

**Comment by buckethead1986** [comment]
Same here, and thanks for all your help!

Robert
