### ISSUE TITLE
debugging issue!

### ISSUE THREAD

**Issue by AlbinaZakirova1804** [learn-co-curriculum/countdown-to-midnight#17]
Hi! I defined in my file method countdown(number) and method has a loop inside. I"m trying to debug it with irb and it gives me a flowing error.
2.3.1 :001 > help

Enter the method name you want to look up.
You can use tab to autocomplete.
Enter a blank line to exit.

>> countdown(7)
Nothing known about .countdown(7)
>>

**Comment by jenmyers** [comment]
Hello!

It looks like this isn't a bug in the curriculum, but an issue you're having elsewhere. That's no problem though! Go ahead and hit the Ask A Question button on learn.co. Either a community member or a technical coach will be able to help you understand what's going on.

Good luck!
