### ISSUE TITLE
Countdown to 0 

### ISSUE THREAD

**Issue by kstough00** [learn-co-curriculum/countdown-to-midnight#20]
the instructions say to countdown to 0. But the Learn test wants you to stop at 1.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
